FROM python:3.9

ENV PYTHONUNBUFFERED=1
ENV DEBUG=1

WORKDIR /csfd_searcher

COPY requirements.txt .
RUN pip install --upgrade pip setuptools
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
