[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"

[tool.coverage.run]
branch = true
omit = [
    "**/tests/*",
    "**/core/*",
    "**/users/*",
    "**/migrations/*",
    "**/manage.py",
    "**/urls.py",
    "**/apps.py",
    "**/admin.py",
    "**/utils/*",
    "**/conftest.py"
]

[tool.coverage.report]
exclude_lines = [
    "def __str__",
    "def __repr__",
]

[tool.black]
line-length = 100
exclude = """
/(
    .git
  | .mypy_cache
  | venv
  | migrations
)/
"""

[tool.isort]
profile = "black"
src_paths = ["searcher", "core"]
multi_line_output = 3

[tool.mypy]
warn_return_any = true
ignore_missing_imports = true
python_version = 3.9
exclude = "migrations"
